twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    #form_themes: ['bootstrap_4_Horizontal_layout.html.twig']
    globals:
        app_environement: '%env(APP_ENV)%'
        appName: 'Vcgen Médias'
        appNameCapital: 'VICGEN MEDIAS'
        appEmail: 'info@vicgenmedias.com'
        appPhone: '+32467633292'
        appAdresse: 'Paris 75000, rue Amandine No 8, Bte 6'
        currency: ' €'
        ashtag: '#'
        appConcepteur: "HL Conception"

when@test:
    twig:
        strict_variables: true